export const MIN_INPUT_LENGTH = 1;

export const MAX_NAME_LENGTH = 15;

export const WATCH_LIMITS = {
  MAX_WATCHES: 10,
};

export const CONDITION_LIMITS = {
  MAX_CONDITIONS: 5,
  MAX_INPUT_LENGTH: 350,
  MAX_ITEM_LENGTH: 50,
  MAX_INCLUDE_TERMS: 5,
  MAX_EXCLUDE_TERMS: 5,
  MAX_TARGET_USERS: 5,
  MAX_TARGET_ROLES: 5,
};
